### ISSUE TITLE
Can’t Restore in-app purchase on iPhone

### ISSUE THREAD

**Issue by Nebukad93** [domoticz/domoticz-xamarin#11]
Hello,

I can’t restore my premium account nor buy on the iPhone app while I can on my iPad. 

I get a message “could not restore your premium account” or “issue with payment : connexion to iTunes Store impossible” on the screen bottom. I have screen shots if needed. I was able to buy premium account with my iPad but can’t benefit on my iPhone.

**Comment by galadril** [comment]
have you tried to reinstall the app.. and then restore of buy again 
(it won't actually buy again if you already bought it!)

**Comment by galadril** [comment]
else i can add you to the beta testers list, to see if the best build in testflight also has that problem

**Comment by Nebukad93** [comment]
Yes, tried to uninstall and reinstall and also from WiFi or cellular. 

I don’t mind trying the beta. What do you need ? e-mail adress ?

**Comment by galadril** [comment]
Is this still the case?

**Comment by Nebukad93** [comment]
No, It's fine now. Thanks
