### ISSUE TITLE
connect on local network

### ISSUE THREAD

**Issue by stanleyk1982** [domoticz/domoticz-xamarin#14]
I use 2 iphones in my house and yesterday app stop work. It work from outside to my public ip and nat https port, but from local network stop work. It write not connect to any network... what happend ?
I try :
change http port in domoticz - no change
access from pc web browser - work
acces from phone web browser - work
disable wifi and use 4g network - work
android phone app - work

I enabled debug in iphone app and in log is connect always to external address, not internal. This is problem because my external IP is not reachable from local network and nat is for https where is certificate for domain name. In android app is option for choose local wifi SSID but not in ios app.

**Comment by galadril** [comment]
Thats weird.. it should try to connect both remote and local if remote is not reachable..

**Comment by stanleyk1982** [comment]
In debug log was connect only on external address. I will try make snapshot from debug this evening at home.

**Comment by stanleyk1982** [comment]
Loading screen: Dashboard
Loading screen: Switches
Loading screen: Scenes
Loading screen: Temperature
Loading screen: Weather
Loading screen: Utilities
GC Authorization granted
GCM: Setup Firebase
JSON Call: https://publicip:port/json.htm?type=plans
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
GCM: connect success
GCM: Push Notification - Device Registered - Token : xxxxxxxxxxxxxxxxxxxxTLQKAfpyuTC8PG4WEojeIxlWoZV5LuneNzR1A9SD4XaC31Dd9c2_FdD9wWtzZ71ny2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb
JSON Call: https://publicip:port/json.htm?type=command¶m=addmobiledevice
Domoticz Full Url: https://publicip:port/json.htm?type=command¶m=addmobiledevice&uuid=E0A7EE43-DE8D-4CE3-8414-2532DAB974AB&senderid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb&name=iPhone&devicetype=iOS10.3.1&active=0
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object
Chyba: žiadne pripojenie na sieť
A task was canceled.
GCM: Device registered on Domoticz
Loading screen: Dashboard
Loading screen: Switches
Loading screen: Scenes
Loading screen: Temperature
Loading screen: Weather
Loading screen: Utilities
GCM: Push Notification - Device Registered - Token : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
JSON Call: https://publicip:port/json.htm?type=command¶m=addmobiledevice
Domoticz Full Url: https://publicip:port/json.htm?type=command¶m=addmobiledevice&uuid=E0A7EE43-DE8D-4CE3-8414-2532DAB974AB&senderid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb&name=iPhone&devicetype=iOS10.3.1&active=0
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
JSON Call: https://publicip:port/json.htm?type=plans
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
A task was canceled.
GCM: Device registered on Domoticz
A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
A task was canceled.
Object reference not set to an instance of an object Loading screen: Dashboard Loading screen: Switches Loading screen: Scenes Loading screen: Temperature Loading screen: Weather Loading screen: Utilities
GCM: Push Notification - Device Registered - Token : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb
JSON Call: https://publicip:port/json.htm?type=command¶m=addmobiledevice
Domoticz Full Url: https://publicip:port/json.htm?type=command¶m=addmobiledevice&uuid=E0A7EE43-DE8D-4CE3-8414-2532DAB974AB&senderid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb&name=iPhone&devicetype=iOS10.3.1&active=0
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
JSON Call: https://publicip:port/json.htm?type=plans
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
A task was canceled.
GCM: Device registered on Domoticz
A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true
********** BANNER AD RECEIVED
A task was canceled.
Object reference not set to an instance of an object Loading screen: Dashboard Loading screen: Switches Loading screen: Scenes Loading screen: Temperature Loading screen: Weather Loading screen: Utilities
GCM: Push Notification - Device Registered - Token : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb
JSON Call: https://publicip:port/json.htm?type=command¶m=addmobiledevice
Domoticz Full Url: https://publicip:port/json.htm?type=command¶m=addmobiledevice&uuid=E0A7EE43-DE8D-4CE3-8414-2532DAB974AB&senderid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy2h5KtyqQVl4dCTIfs23qyS4cac3Hk4vAb&name=iPhone&devicetype=iOS10.3.1&active=0
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true
JSON Call: https://publicip:port/json.htm?type=plans
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true&favorite=1
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
********** BANNER AD RECEIVED
JSON Call: https://publicip:port/json.htm?type=devices&filter=temp&used=true
********** BANNER AD RECEIVED
A task was canceled.
GCM: Device registered on Domoticz
A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object A task was canceled.
Object reference not set to an instance of an object JSON Call: https://publicip:port/json.htm?type=scenes
********** BANNER AD RECEIVED
A task was canceled.
Object reference not set to an instance of an object JSON Call: https://publicip:port/json.htm?type=devices&filter=temp&used=true
A task was canceled.
Object reference not set to an instance of an object JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true
********** BANNER AD RECEIVED
A task was canceled.
Object reference not set to an instance of an object Zapnúť prepínač: ALARM Action Call: https://publicip:port/json.htm?type=command¶m=switchlight&idx=1299&switchcmd=On&passcode=
A task was canceled.
Cancel Pressed
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true
Zapnúť prepínač: LusterKuchyna
Action Call: https://publicip:port/json.htm?type=command¶m=switchlight&idx=92&switchcmd=On&passcode=
A task was canceled.
Object reference not set to an instance of an object A task was canceled.
JSON Call: https://publicip:port/json.htm?type=devices&filter=all&used=true
A task was canceled.
Object reference not set to an instance of an object

**Comment by galadril** [comment]
Thanks, ill test this issue soon

**Comment by stanleyk1982** [comment]
Thank you, if you need some more logs or testing, just let me know

**Comment by galadril** [comment]
Too bad that i have 2 weeks holiday at this moment.. so please be patient 🍶

**Comment by galadril** [comment]
sry do you still have that issue?

**Comment by stanleyk1982** [comment]
no, is ok now. I think after ios update it was good.
