### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by charlyhue** [domoticz/domoticz-xamarin#16]
Hello,

When I try to login in the ios app I get Unauthorized error.
I use an admin user who work on webui.

**Comment by galadril** [comment]
Thats weird, do you use https?>

**Comment by charlyhue** [comment]
Yes,
I think the problem comes from Cloudflare because I do not have this problem locally...

**Comment by galadril** [comment]
that probably the case

**Comment by charlyhue** [comment]
But I can not find the exact problem...

**Comment by galadril** [comment]
HttpClient has a default timeout of 7 seconds, we have the timeout on 10 seconds.
https://github.com/domoticz/domoticz-xamarin/blob/master/NL.HNOGames.Domoticz/NL.HNOGames.Domoticz/Data/ConnectionService.cs
