### ISSUE TITLE
Notification no sound in iOS

### ISSUE THREAD

**Issue by lily148** [domoticz/domoticz-xamarin#17]
Hi,

I purchased the in-app version for the notification purpose.
but it seem like the notification arrived without any sound / tone. Any special setting I need to set in my iPhone?

**Comment by DewGew** [comment]
I have the same issue..

**Comment by lily148** [comment]
Still no update? :(

**Comment by galadril** [comment]
This is actually a thing that should be build in the Domoticz system.. the message payload should contains the sound property to get a sound in iOS.

This file should be changed in Domoticz
https://github.com/domoticz/domoticz/blob/95e2be251f07af94f8068172b0fd4473bbbb8792/notifications/NotificationGCM.cpp

Here is more info on FCM notification messages:
https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

More on the properties that could be entered in the notification json payload
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

Can you please make an issue

**Comment by galadril** [comment]
Thanks for creating the issue.. i've supplied more info on that matter.. ill keep this issue closed on this project
