### ISSUE TITLE
Implement Geofences

### ISSUE THREAD

**Issue by galadril** [domoticz/domoticz-xamarin#21]
Find a way to implement geofences for iOS

**Comment by galadril** [comment]
Added a location picker to the geofence settings:
![image](https://user-images.githubusercontent.com/14561640/78790996-97214880-79af-11ea-9b42-601592d19a16.png)

**Comment by FearNaBoinne** [comment]
Initial tests look promising (v1.16), however it would be nice if the Radius could be set using a resizable circle, like for instance in the Pilot app (slider) or the iOS built-in Geo-reminders (draggable circle perimeter), so you get an idea of what range you're covering on the map...

**Comment by galadril** [comment]
Good idea.. Maybe for a second version if it's too difficult in Xamarin for
now.

Have you tried nfc?

Op wo 15 apr. 2020 21:32 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by FearNaBoinne** [comment]
I did try NFC, but do not have NDEF encoded tags available right now...

But whenever it doesn't complete correctly, for instance due to an incorrect type of tag, a stack error or - as in this example - by cancelling the scan dialog, the "register a NFC Tag" screen doesn't go away:
https://cdn.discordapp.com/attachments/451724755431587842/700076075367137380/NFC_attempt_-_cancel_dialog.mp4

**Comment by galadril** [comment]
Good point, Ill fix that quickly

Op wo 15 apr. 2020 22:25 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by FearNaBoinne** [comment]
I will dig up my NTAG stickers and program one with some NDEF data to test with later... Just remind me if I haven't responded by Friday, cause I am both busy and have a brain like a steel sieve!

**Comment by galadril** [comment]
Ok thanks, ill let you know!
A new version with the loading fixed comes in testflight tomorrow

Op wo 15 apr. 2020 om 22:38 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by FearNaBoinne** [comment]
Getting that update message will be a good reminder that I need to get them NTAGs...  ;)

**Comment by FearNaBoinne** [comment]
(PS: Are you Dutch? I saw a bit of an email header in Dutch earlier...)

**Comment by galadril** [comment]
yes i am :D

Op wo 15 apr. 2020 om 22:43 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by FearNaBoinne** [comment]
Ik ook...  👍

**Comment by FearNaBoinne** [comment]
Upgraded to 0.1.11 (121) beta version.

Haven't done an NDEF tag yet, but can confirm it now correctly handles cancellations and unsupported tags... Also haven't seen the stack error message again so far!

**Comment by galadril** [comment]
Cool..

**Comment by FearNaBoinne** [comment]
NFC seems to be working... 

A nice addition would be if we could SEARCH in the switch assignment dialog... With hundreds of toggles, switches and scenes this can be hard to navigate.

**Comment by FearNaBoinne** [comment]
GeoFencing doesn't seem to be working reliably. When I went to buy bread at the local supermarket, it looks like it did NOT register me leaving, but DID register me coming back, according to the Domoticz log for the linked switch:
https://cdn.discordapp.com/attachments/677915413748908099/700670875690598420/unknown.png

**Comment by galadril** [comment]
Can you make a video on the nfc working?

Op vr 17 apr. 2020 13:38 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by galadril** [comment]
About the Geofences reliabilty.. thats can be multiple causes..

- Bad 4G quality? 
- Don't make too small radius (round 300 is the best value)?
- Did you saw the notification? but did the switch not trigger? (could be a connectivity issue to domoticz). The geofence notification option is local.. so then you rule out that it could connect to Domoticz..

**Comment by FearNaBoinne** [comment]
> 
> Can you make a video on the nfc working? (i need a video to supply to apple on the next update.. i dont own a device with NFC support from Apple...)

Will do!  :)

**Comment by FearNaBoinne** [comment]
> 
> 
> About the Geofences reliabilty.. thats can be multiple causes..
> 
>     * Bad 4G quality?
> 
>     * Don't make too small radius (round 300 is the best value)?
> 
>     * Did you saw the notification? but did the switch not trigger? (could be a connectivity issue to domoticz). The geofence notification option is local.. so then you rule out that it could connect to Domoticz..

4G was fine
Radius is currently set to 50m to make it easier to test, but at this occasion I was ~1km away from the setpoint
AFAICT from the lock screen history, there was no leave notification, only an entry notification...

**Comment by galadril** [comment]
hmm

**Comment by FearNaBoinne** [comment]
Something like this?

https://cdn.discordapp.com/attachments/451724755431587842/700696193746862090/RPReplay_Final1587129336.MP4

**Comment by FearNaBoinne** [comment]
BTW, during the attempt to make above clip, I had one (single) stack error message...

**Comment by galadril** [comment]
Hmmm

Op vr 17 apr. 2020 22:01 schreef Francesco Peeters (AKA CescoAiel) <
notifications@github.com>:

**Comment by FearNaBoinne** [comment]
Last three days the GeoFences seems to have mostly worked correctly, but there's also been another episode where I do see an "ON" but no "OFF".
![Log example](https://cdn.discordapp.com/attachments/677915413748908099/702648606167007282/unknown.png)

Is there a way to keep track of these events reliably in the app?

**Comment by galadril** [comment]
Im going to close this issue for now, as the feature is implemented as documented for Xamarin Forms.

There are a lot of possible issues that you can have with Geofences..


Next to that.. The minimal radius should be not lower then 200 to keep it as reliable as possible!
