### ISSUE TITLE
Feature request: iOS Quick Actions + 3d Touch

### ISSUE THREAD

**Issue by FearNaBoinne** [domoticz/domoticz-xamarin#27]
It would be nice if a springboard force-tap (or long tap) menu could be created to provice quick access to a limited number of often used switches/scenes/functions (NFC Tag Reader)

**Comment by galadril** [comment]
Just for me a link to how to do it in Xamarin..

![image](https://user-images.githubusercontent.com/14561640/79571145-fde2e800-80ba-11ea-9fb4-5ae0df40189b.png)

Should be possible with Xamarin iOS:
https://blog.verslu.is/xamarin/xamarin-forms-xamarin/3d-touch-your-xamarin-forms-app-apply-pressure-to-icon-area/

**Comment by galadril** [comment]
I cant really do NFC, Qr code scan or Speech for example.. as its a fixed list.. 
I can't enable or disable quick actions if NFC is disabled in the app.


What i can do is make quick actions to
- Dashboard
- Switches
- Scenes
- Temperature
- Weather
- Utilities

Then the next point:
"You can only store up to 4 Quick Actions per app."

soo i  would suggest:
- Dashboard
- Switches
- Scenes
- Temperature
???

**Comment by galadril** [comment]
Another topic.. only a fixed set of icons for application quick actions is allowed:
https://docs.microsoft.com/en-us/xamarin/ios/platform/3d-touch#Quick_Actions

![image](https://user-images.githubusercontent.com/14561640/79572191-cd03b280-80bc-11ea-97a5-94b6bdca1aee.png)

**Comment by galadril** [comment]
I did some reading.. and i can set dynamic shortcuts and custom icons..
so im going to suggest

- NFC scan
- QR code scan
- Speech command

**Comment by FearNaBoinne** [comment]
Wish I could contribute more than ideas, but time (to immerse myself in the code and make additions) is something I lack most of all lately...

**Comment by FearNaBoinne** [comment]
Downloaded 0.1.12, and it *does* show (only) the NFC Scan shortcut, but when I click it, it just opens the app, but doesn't immediately start the scanner...

**Comment by galadril** [comment]
Thats weird (as it worked here on my devices on Android)... and speech/qrcode??

**Comment by galadril** [comment]
@FearNaBoinne what do you think of the icons that i should use??

I can only use the next icons:
Home Screen Quick Action Icons
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/system-icons/

**Comment by FearNaBoinne** [comment]
None of the icons are really very good, but going with that set, from the "Home Screen Quick Action Icons" I'd probably use "Message" (or  "Audio") for speech, "Capture Photo" for QR and "Update" (or "Share") for NFC...

All options only start the app, without initiating the requested action, and for some reason I am seeing the NFC option twice.
Furthermore, all of them seem to have the description "Register a ****":
https://cdn.discordapp.com/attachments/677915413748908099/702139360060899418/image.png

**Comment by FearNaBoinne** [comment]
LOL, so now you can blame me if people do not like the icons...  :P

**Comment by FearNaBoinne** [comment]
Icons are correct, shortcuts still aren't working...

**Comment by galadril** [comment]
pff i cant really test this.. as i don't have a Touch3D enabled device here at the moment (one @ another locations, but yeahh Corona.. )

I tested this on Android (as Xamarin is multiplatform).. and there it all works...

**Comment by FearNaBoinne** [comment]
I have no problem testing stuff for you, but I don't know the Xamarin platform, so no clue why it's not calling the correct actions.

I will try removing and reinstalling the 0.1.14

**Comment by galadril** [comment]
i think i've overlooked something.. new build 0.1.15 is coming.. think its fixed now

**Comment by FearNaBoinne** [comment]
Just downloaded and installed 0.1.15... Seems to be working now... Will test some more in the morning!

Only last remark is the description under each shortcut...
"Register a (Speech Comma...|QR Code|NFC Tag)"
I don't know whether it is possible to change those, but it'd make more sense (if possible) to have:
"Listen for a Speech Command"/"Scan a (QR Code|NFC Tag)"

https://media.discordapp.net/attachments/677915413748908099/702645233715904662/image.png

**Comment by galadril** [comment]
Great that it's working!
