### ISSUE TITLE
Feature request: Advanced ibeacon positioning

### ISSUE THREAD

**Issue by derekoharrow** [domoticz/domoticz-xamarin#38]
I love this app, and really like the ibeacon support. I'm planning to use it a lot more to detect when people (or rather their phones) are in certain rooms.

I believe that with the current setup you have to attribute one beacon to one switch, which means lots of switches - one per beacon per person. While that's doable, it would be much more convenient to be able to use a selector switch and have it changed to a state representing the nearest beacon.

If suggest that if a normal switch is used, it functions as today, but if a selector switch is chosen, you are prompted for the value to set it to. This would probably also require only triggering for the strongest signal.

**Comment by galadril** [comment]
You could make one selector switch (multi value per room). Then use that
one switch voor all rooms.

This is how I use it

Op ma 29 jun. 2020 22:20 schreef derekoharrow <notifications@github.com>:

**Comment by derekoharrow** [comment]
Ah. didnt realise it does that - perfect!!

**Comment by derekoharrow** [comment]
> You could make one selector switch (multi value per room). Then use that one switch voor all rooms. This is how I use it Op ma 29 jun. 2020 22:20 schreef derekoharrow <notifications@github.com>:
> […](#)

Sorry - a follow up if I may...

I can choose a selector and value, but what does it do when you leave the area? 

How have you set yours up?

Thanks again.

**Comment by galadril** [comment]
It goes to the off state

Op ma 29 jun. 2020 22:41 schreef derekoharrow <notifications@github.com>:
