### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by DewGew** [domoticz/domoticz-xamarin#39]
I dont get any notifications. I have checked my phone settings. We I test i settings mobile it works but not from any of my dzvents scripts or in device notifications. Any suggestions?

**Comment by galadril** [comment]
So if you hit the 'test' button on the mobile devices settings screen it works.. which means that notifications works for the mobile app.

So this looks like this needs to be fixed somewhere in Domoticz instead of the apps. right?

**Comment by DewGew** [comment]
How do i debug this? Email, Browser notification works.

**Comment by galadril** [comment]
@gizmocuz do you have an idea?

**Comment by DewGew** [comment]
Sorry about this. I found the isssue. Google cloud message was inactive in settings :)
